### ISSUE TITLE
Nested Lists appear to be broken in spec

### ISSUE THREAD

**Issue by gtoast** [podlite/podlite-specs#9]
In the part of the spec that illustrates multi-level lists the rendered example list aren't displayed as `<li>'s` and aren't nested. See the part the spec that has the list of "Animals" and "Phases"

**Comment by zag** [comment]
Yes, thank you, that really is a mistake. 
I checked on the playground, and it looks like the error occurred while preparing the HTML version. 

<img width="921" alt="image" src="https://github.com/podlite/podlite-specs/assets/31441/0533f3fe-706f-4dcd-bdc4-718716af3396">

[exmaple for check at pod6.in](https://pod6.in/#p=%0A++%3Ditem1++Animal%0A++%3Ditem2+++++Vertebrate%0A++%3Ditem2+++++Invertebrate%0A++%0A++%3Ditem1++Phase%0A++%3Ditem2+++++Solid%0A++%3Ditem2+++++Liquid%0A++%3Ditem2+++++Gas%0A++%3Ditem2+++++Chocolate)

Thank you so much!
